spring:
  application:
    name: banque-service

  zipkin:
    service:
      name: banque-service

  data:
    mongodb:
      uri: mongodb://mngadmin:alae.2001@localhost:27017/gold-banking?authMechanism=SCRAM-SHA-1&authSource=admin


server:
  port: 7050


banque:
  params:
    x: 11
    y: 12

