spring:
  application:
    name: customer-service

  zipkin:
    service:
      name: customer-service

  data:
    mongodb:
      uri: mongodb://mngadmin:alae.2001@localhost:27017/gold-banking?authMechanism=SCRAM-SHA-1&authSource=admin


server:
  port: 7080


customer:
  params:
    x: 5
    y: 6
