spring:
  application:
    name: product-service

  zipkin:
    service:
      name: product-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: alae.2001


  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 7040


credit:
  params:
    x: 56
    y: 79
